# Copyright (c) 2026 The State Key Laboratory of Blockchain and Data Security, Zhejiang University
# SPDX-License-Identifier: Apache-2.0

[toolchain]
channel = "1.94"
components = ["clippy", "rustfmt"]